package com.limapps.base.utils

const val COLOMBIA_CODE = "CO"
const val MEXICO_CODE = "MX"
const val BRAZIL_CODE = "BR"
const val ARGENTINA_CODE = "AR"
const val CHILE_CODE = "CL"
const val URUGUAY_CODE = "UY"
const val PERU_CODE = "PE"
const val COSTA_RICA_CODE = "CR"
const val ECUADOR_CODE = "EC"
const val COLOMBIA_CURRENCY_CODE = "COP"
const val MEXICO_CURRENCY_CODE = "MXN"
const val BRAZIL_CURRENCY_CODE = "BRL"
const val ARGENTINA_CURRENCY_CODE = "ARS"
const val CHILE_CURRENCY_CODE = "CLP"
const val URUGUAY_CURRENCY_CODE = "UYU"
const val PERU_CURRENCY_CODE = "PEN"
const val COSTA_RICA_CURRENCY_CODE = "CRC"
const val USD_CURRENCY_CODE = "USD"
