package com.limapps.base.utils

private const val COMMA_SYMBOL = ','
private const val DOT_SYMBOL = '.'

enum class CountryCurrency(
        val countryCode: String,
        val currencyCode: String,
        val currencySymbol: String,
        val decimalSeparator: Char,
        val groupingSeparator: Char,
        val minDecimals: Int,
        val maxDecimals: Int
) {

    ARGENTINA(ARGENTINA_CODE, ARGENTINA_CURRENCY_CODE, DOLLAR_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 2, 2),
    COLOMBIA(COLOMBIA_CODE, COLOMBIA_CURRENCY_CODE, DOLLAR_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 0, 0),
    MEXICO(MEXICO_CODE, MEXICO_CURRENCY_CODE, DOLLAR_SYMBOL, DOT_SYMBOL, COMMA_SYMBOL, 2, 2),
    BRAZIL(BRAZIL_CODE, BRAZIL_CURRENCY_CODE, REAL_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 2, 2),
    CHILE(CHILE_CODE, CHILE_CURRENCY_CODE, DOLLAR_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 0, 0),
    URUGUAY(URUGUAY_CODE, URUGUAY_CURRENCY_CODE, DOLLAR_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 2, 2),
    PERU(PERU_CODE, PERU_CURRENCY_CODE, SOL_SYMBOL, DOT_SYMBOL, COMMA_SYMBOL, 2, 2),
    COSTA_RICA(COSTA_RICA_CODE, COSTA_RICA_CURRENCY_CODE, COLON_SYMBOL, DOT_SYMBOL, COMMA_SYMBOL, 0, 0),
    ECUADOR(ECUADOR_CODE, USD_CURRENCY_CODE, DOLLAR_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 2, 2),
    DEFAULT("", "", DOLLAR_SYMBOL, COMMA_SYMBOL, DOT_SYMBOL, 0, 0)
}