package com.limapps.base.models.orders

const val ID = "id"
const val STATE = "state"
const val STATE_MESSAGE = "state_message"
const val PLACE_AT = "place_at"
const val PLACE_AT_PATH = "place_at_path"
const val EXPEDITER = "expediter"
const val RT = "responsible"
const val TOTAL = "total"
const val CAN_BE_CANCEL = "can_be_cancel"
const val TIP = "tip"
const val DELIVERY_METHOD = "delivery_method"
const val ORDER_PLACE_AT = "order_place_at"
const val DATABASE = "database"
const val FINISHED_AT = "finished_at"
const val STORE = "store"
const val STORE_TYPE = "store_type"
const val NAME = "name"
const val IMAGE = "image"
const val TYPE = "type"
const val PHONE = "phone"
const val FAKE = "fake"
const val STOREKEEPER_ID = "storekeeper_id"
const val STOREKEEPER_NAME = "storekeeper_name"
const val STOREKEEPER_TYPE = "storekeeper_type"
const val STOREKEEPER_PHONE = "storekeeper_phone"
const val STOREKEEPER_PICTURE = "storekeeper_profile_pic"